module UI
end

require_dependency 'ui/developer_list/developer_list_read_model'
require_dependency 'ui/project_list/project_list_read_model'
require_dependency 'ui/project_details/project_details_read_model'
require_dependency 'ui/project_approximate_end/project_approximate_end_read_model'
require_dependency 'ui/order_list/order_list_read_model'
